### ISSUE TITLE
possible to open in New Window?

### ISSUE THREAD

**Issue by Dwight-Schrute** [WesleyBranton/Outlook.com-mailto#16]
Great extension, and a part of my daily workflow... thank you.

Is it possible to have the mailto links open in a new window if my about:config "browser.link.open_newwindow" is set to 3 (divert new window to a new tab)?

The idea being; only this extension can override that browser setting which I like.

It looks like that async function is at /background.js [77] but how would you override the default browser behavior first? or is there a simpler work around.
`if (tabInfo.url == 'about:blank') `
`{browser.tabs.update(requestDetails.tabId, {url: link  });`
` } else `
`{browser.tabs.create({index: tabInfo.index + 1,url: link});`
` } `

id be happy to pull and contribute a new branch to this project since its been a huge help, but this is out of my shallow scope of knowledge and id need a hint or two.

cheers.

**Comment by Dwight-Schrute** [comment]
I Def bit off more than I can chew there. Yes please if you could add the feature that would be awesome.
Just being able to look at the difference in the code will help me understand, as im super-green.

**Comment by WesleyBranton** [comment]
Not a problem. Thanks for the idea. I'll implement it and then feel free to ask any questions if you want afterwards.

**Comment by WesleyBranton** [comment]
So, I made a few other minor changes after adding the feature, so the feature that you requested is really only the commit that I attached to this issue. The pull request has all of the changes, many of which have nothing to do with the feature that you wanted, so if you want to see what code was required, just comparing the commit is probably better for you to see.

Not much changed for the code in the `openTab()` function, other than the addition of the new `if` statement in lines 105-110. The code still opens a new tab first with the correct email link, although I tweaked the code there a bit so that it saves information about the tab that's created so I can easily get the tab ID. The new if statement only runs if the user has changed the setting to open links in a new window. Fortunately, the [Windows API in Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows) will automatically move the tab if you supply the tab ID when you [create a new window](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create).

The only other small change I made (it's in [this commit](https://github.com/WesleyBranton/Outlook.com-mailto/pull/17/commits/f46ecff51a4f20e9038214c10e8dfab748411118), not the one attached to this issue because it was an after thought) is to add an `active` value to the new tab that gets created. If the user wants the tab in a new window, it's not set to be active. If the user wants the tab in the same window, it's set to be active.

The reason for this is because the tab gets created first in the current window and then moved to a new window (if the user wants), it sometimes changes what tab is set as the active tab in the current window that the user is viewing. So if the user wants the tab moved to a new window, setting the `active` value to `false` makes sure that the current window focused tab doesn't change.

Other than that, the only real big change in that file would be the addition of the `updatePrefs()` function. This is just what I use to keep the variable in the file in sync with what the user has in the settings. It's run [each time the user changes a setting](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged). I later changed the code a bit so that the Outlook version the user wants (personal or organization) is updated the same way.

The alternative is the use the [Storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) to [read the user settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get) each time they click the email link, but that can have some very minor performance issues since reading the storage can be pretty slow. Generally, I find that the approach I used (using a variable in the file and updating it with each change) works a bit nicer.

In the options folder, those changes were just to add the new setting into the UI for the user to click.

Hopefully that's a good overview of how I added the new feature and hopefully my explanation will help you understand the code in detail if you plan on reviewing it as a learning experience.

If you have any other questions about the code, feel free to ask. Always happy to help people who are interested in coding or developing Firefox add-ons.

Thanks again for the feature idea! I definitely wouldn't have thought of it.
